apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app.kubernetes.io/name: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: blog
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blog
    spec:
      imagePullSecrets:
        - name:  gitlab-registry
      containers:
        - name: blog
          image: blog
          ports:
            - containerPort: 80
