[project]
name = "public-notebook"
version = "0.1.0"
description = "My personal website"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ablog>=0.11.12",
]

[dependency-groups]
dev = [
    "jupyter-book>=1.0.4.post1",
]
