controller:
  publishService:
    enabled: true

  service:
    annotations:
      service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: 'true'

  config:
    use-proxy-protocol: 'true'

defaultBackend:
  enable: true
